### ISSUE TITLE
dfshack exits when handling files with special characters in the name

### ISSUE THREAD

**Issue by buddy65** [LinuxMercedes/dfshack#2]
For example:

open("/mnt/dfs/blspcy/Users/blspcy//AppData/Roaming/Mozilla/Firefox/Profiles/p6re69h6.default/storage/default/https+++drive.google.com", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 4
fstat(4, {st_mode=S_IFDIR|0700, st_size=0, ...}) = 0
getdents(4, /* 5 entries */, 32768)     = 136
getdents(4, /* 0 entries */, 32768)     = 0
close(4)                                = 0
write(2, "Nested quantifiers in regex; mar"..., 206) = 206

and 

openat(AT_FDCWD, "/mnt/dfs/blspcy/Users/blspcy//linuxhome/.mozilla/firefox/pr2nwfii.default/features/{a9081ce0-ddf0-4222-83d0-6c9e9fd5c327}", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 4
fstat(4, {st_mode=S_IFDIR|0700, st_size=0, ...}) = 0
getdents(4, /* 5 entries */, 32768)     = 184
getdents(4, /* 0 entries */, 32768)     = 0
close(4)                                = 0
write(2, "Unescaped left brace in regex is"..., 226) = 226

**Comment by LinuxMercedes** [comment]
I believe the issue is [here](https://github.com/LinuxMercedes/dfshack/blob/master/dfshack.pl#L246): `$dirname` should be `\Q$dirname\E` to keep the contents of `$dirname` from being parsed as a regex. There are a few other regexes like that as well. Let me put together a patch for you to test!
